### PR TITLE
HTML & CSS 3: Building with backgrounds and gradients 

### PR DESCRIPTION
**Pull request by JasemDuncan**
_**Hello there**_

**_\\------------------- This a clone from Apple Inc. Website -------------------------/_**

In this PR I used:

- HTML & CSS.
- Background images and Gradients for the menu.

Greetings.

_\\----------------------------- **Jasem Valencia**------------------------------------/_

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Isabirye Isabirye**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Good job working with background images! 🌟**

There are still some required checks you need to fulfill in order to continue to the next project, so hang in there! 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] The main image should take 100% of the screen width regardless of its size. Your page has a lot of white space on the sides at the moment.

- [ ] Change the font of the main text to look closer to the text in the original site. 
[Google fonts](https://fonts.google.com/) is a good place to find webfonts.
Screenshot_2020-04-15 Apple(2)
Screenshot_2020-04-15 Apple(3)


- [ ] Make sure you align vertically the text and elements of your navbar. Compare your version and the original one below:
Screenshot_2020-04-15 Apple
Screenshot_2020-04-15 Apple(1)

----

- [ ] The elements at the bottom of the main image should be links, notice how the link you to other pages in the[ original website](https://web.archive.org/web/20140301004610/http://www.apple.com/) Check the requirement below and make sure to fulfill it. 
Screenshot_2020-04-13 dist html_css building_with_backgrounds_and_gradients md · master · Microverse guides tse code_review

----

- [ ] [OPTIONAL] Be more semantic! Use the `footer` tag around the divs that make the role of the page footer. Use a `main` tag for the div with the main background image.

[Important] You are using a lot of divs in this project when you could use flex positioning or block elements to achieve the same look in a much more semantic and organized way. Try to block your page by semantic areas, if everything on the top looks to be inside the same element, make a parent element, if text is multiline but has the same font use just one tag and work with the width and margins.

- [OPTIONAL] Usually CSS classes only use lower case characters, read [this guide here](https://en.bem.info/methodology/naming-convention/) on CSS writing style and best practices.

If the page looks correct on your monitor you can use your [browser responsive tools](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) to make sure the page still looks correct on slightly wider monitors.

------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by JasemDuncan** [comment]
Hello, many thanks for the required changes. I already did. 
Thanks again

**Comment by lekegitrepo** [comment]
### Hi @JasemDuncan 👏 
### Good job 💪 but you still need to enable stickler for this project.

**_Enable stickler for the project and submit for review._**

### Reviewed by Temitayo Adeleke.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Request changes

**Comment by JasemDuncan** [comment]
Hi @lekegitrepo, sorry about the stickler but I used the Set-up Stylelint in your local environment to validate the style.
So in my local environment, the style has no errors. But no problem I already turn on sticklers.

Thanks.
Jasem Valencia

**Comment by addod19** [comment]
## Pull request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @JasemDuncan, you have done a great job so far 👍 we are almost there 😄 . In order to improve our project, let us address the following issues. Kindly find comments below:
- Let us add a description to our README file and also add our email to the ```author``` section
- Let us fix the horizontal scroll
- Kindly enable stickler for the repo so that, as TSE's we can easily validate and review. Kindly visit stickler-ci.com so you enable stickler to check for errors or warnings

Kindly address these issues and submit another code review 👍 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by JasemDuncan** [comment]
Hi @addod19, thank you for the suggestions I already did.

Thanks
Jasem Valencia

**Review by rOluochKe — APPROVED** [review]
Hello @JasemDuncan 
### You have done well and for also making changes from the previous reviews :clap: I, therefore, approve of the project. It passes the review. Congratulations :boom: :100:
### You can merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Comment by JasemDuncan** [comment]
Thanks sir.

**Pull request merged**
